### ISSUE TITLE
session.cmd returns broken string when command is too long

### ISSUE THREAD

**Issue by olavph** [avocado-framework/avocado-vt#231] opened 2015-11-03 13:58 UTC
When the command string passed to session.cmd exceeds ~60 characters, the returned string contains bits of the passed command and some seemingly random characters.

Below, I've sent the same command twice, the second time with extra white spaces, and I'm printing the returned string. There is an extra unwanted line before the actual command output.

08:47:53 client           L1042 DEBUG| Sending command: echo 12345
08:47:53 client           L1042 DEBUG| Sending command: echo $?
08:47:53 test              L0029 INFO | Command output:
12345

08:47:53 client           L1042 DEBUG| Sending command: echo                                                   12345
08:47:53 client           L1042 DEBUG| Sending command: echo $?
08:47:53 test              L0033 INFO | Command output:
echo                                                   12<                                                12345
12345

**Comment by lmr** [comment] 2015-11-03 19:25
I think that's related to the way we start the subprocess and the worker threads in aexpect. I'm a bit short on time to debug this, so unless @clebergnu and @ldoktor have some time, this is going to take a little while to be worked on.

**Comment by clebergnu** [comment] 2015-11-03 19:44
I can give it a look in the next few days.

**Comment by ldoktor** [comment] 2015-11-04 14:00
Hmm, there is something nasty happening here. I played with it and executing `bash`, everything works well. But when I execute `ssh`, it injects random characters:

```
raw_data = 'echo 00000000000000000000000000000000000000000000000000\r<000000000000000000000000000000000000000000000000000                         \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x080000000000000000000000000\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08                         \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x080000000000000000000000000\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08                         \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x0800000000000000000\r\n000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\r\n[root@atest-guest ~]# '
```

then we remove the `\r`. The `\x08` (backspace) characters are evaluated while writing into the file. Even weirder is, that there are 25 spaces and 50 backspaces, which results in `0` being also erased (in this example there are 288 `0`s, but only 238 are written in the output file.

What's even more interesting is the `<` character, which was always on the position 50 during my tests. I tried very long strings, I tried sending the strings per-partes with 1s delay, no difference. I even tried SIGSTOP the command and send the full string at once and then SIGCONT, without any difference.

I also googled around and the only mentioning I found is __ALWAYS__ use -echo when talking to ssh from a program. And yes, when I set `stty -echo` I can send any commands and they just works.


Anyway these are only problems in the `tty echo`. Commands are not affected which means it executes what you provided. I also haven't seen any problems in the results (when I send 240 chars, it echoes 240 chars). The same in your example, you send `echo 12345`, in the output you see corrupted output of echo `echo 12< 12345` and then the actual response, which is unaffected `12345`.

I'm wondering whether disabling `echo` and injecting commands into the results (so faking the echo) would be less confusing, what do you think, guys...

**Comment by lmr** [comment] 2015-11-04 14:52
@ldoktor I guess we can simply disable `echo`.

**Comment by olavph** [comment] 2015-11-04 15:57
In my tests, the command was also always executed. My workaround was to simply ignore the first line in the output.
I think the -echo might indeed work.

**Comment by ldoktor** [comment] 2015-11-06 23:14
Well I played with it a bit more, the fix would be:

```diff
diff --git a/virttest/virt_vm.py b/virttest/virt_vm.py
index f589bd9..c9b6be2 100644
--- a/virttest/virt_vm.py
+++ b/virttest/virt_vm.py
@@ -931,6 +931,11 @@ class BaseVM(object):
                                       interface=neigh_attach_if)
         session.set_status_test_command(self.params.get("status_test_command",
                                                         ""))
+        os_type = self.params.get('os_type')
+        if os_type == 'linux':
+            session.cmd("stty -echo")
+        elif os_type == 'windows':
+            session.cmd("echo off")
         self.remote_sessions.append(session)
         return session
 

```

But it's a bit of "dark-magic" and more importantly the `session-avocado-vt-*` files are not readable, because we see only responses:

```
2015-11-06 21:53:42: [root@atest-guest ~]#
2015-11-06 21:53:42: stty -echo
2015-11-06 21:53:42: [root@atest-guest ~]#
2015-11-06 21:53:42: 0
2015-11-06 21:53:42: [root@atest-guest ~]#
2015-11-06 21:53:42: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

I think it's better to keep the echo enabled. Yes, it's confusing, but you have at least something to start with. Even partial/corrupted input is easier to assign to the "Sending command..." from job.log.

PS: I tried all kind of variants with `raw,-raw,sane,...` on aexpect side and in guest, without any difference.

**Comment by ldoktor** [comment] 2015-11-06 23:27
I played with it a bit more and the `<` character plus all the repeating/removed characters are due to `cols` in tty, even though `stty` reports `rows 0 cols 0` it breaks in `80` chars. When I manually set it to `30` chars, the output looks like this:

```
Sending command: echo 1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz
echo \r
<-guest ~]# echo 1         \x08\x08\x08\x08\x08\x08\x08\x08\x08234567890\r
< echo 1234567890a         \x08\x08\x08\x08\x08\x08\x08\x08\x08bcdefghij\r
<567890abcdefghijk         \x08\x08\x08\x08\x08\x08\x08\x08\x08lmnopqrst\r
<efghijklmnopqrstu         \x08\x08\x08\x08\x08\x08\x08\x08\x08vwxyz1234\r
<opqrstuvwxyz12345         \x08\x08\x08\x08\x08\x08\x08\x08\x0867890abcd\r
<yz1234567890abcde         \x08\x08\x08\x08\x08\x08\x08\x08\x08fghijklmn\r
<90abcdefghijklmno         \x08\x08\x08\x08\x08\x08\x08\x08\x08pqrstuvwx\r
<ijklmnopqrstuvwxy         \x08\x08\x08\x08\x08\x08\x08\x08\x08z12345678\r
<stuvwxyz123456789         \x08\x08\x08\x08\x08\x08\x08\x08\x080abcdefgh\r
<34567890abcdefghi         \x08\x08\x08\x08\x08\x08\x08\x08\x08jklmnopqr\r
<cdefghijklmnopqrs         \x08\x08\x08\x08\x08\x08\x08\x08\x08tuvwxyz12\r
<mnopqrstuvwxyz123         \x08\x08\x08\x08\x08\x08\x08\x08\x084567890ab\r
<wxyz1234567890abc         \x08\x08\x08\x08\x08\x08\x08\x08\x08defghijkl\r
<7890abcdefghijklm         \x08\x08\x08\x08\x08\x08\x08\x08\x08nopqrstuv\r
<ghijklmnopqrstuvw         \x08\x08\x08\x08\x08\x08\x08\x08\x08xyz\r

1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz\r

```
_note: I modified the `aexpect` to replace `\r` with `\\r\n` and `\x08` with `\\x08` to see the real output. Without this modification it removes part of the output because the number of `\x08` (backspace) is greater than number of ` `. And aexpect removes the `\r` by default (because the output was spammed with random characters)._

When you look at the output, you can notice the pattern. It works the same as if you set `stty cols 30` on your `80` chars terminal. It writes, than it's suppose to wrap it so it returns the carrier (`\r`) and then writes `<` to notify you, that the command was wrapped (yeah, how long I had been thinking about where the `<` comes from) and keeps writing. It also needs to clean the line so it uses some `\x08` (backspace) and ` ` (spaces) to overwrite it.

OK, so we know whom to blame. Now how we can solve it. Setting `cols = 0` doesn't work. Using big number helps, but still you can come up with a command with greater size.

Last but not least, we can start doing some fancy stuff like:

```python
aexpect-helper: (around line 150, instead of the data = data.replace("\r", ""))
                out = []
                for line in data.split("\r"):
                    while '\n' in line:
                        _, line = line.split('\n', 1)
                        out.append(_ + "\n")
                    if ' \x08' in line:
                        line = re.split(r' +\x08+', line, 1)
                        line = line[0][-1] + line[1]
                    out.append(line)
                data = "".join(out)
```

Uff, this works for all sane `cols` setting (when the cols is greater than PS1), tested with `cols` = 30, 80, 240, 999999.

Anyway I can't guarantee it won't corrupt your output (eg. when using some crazy outputs). We should probably find the exact `re` pattern for the `80` cols size (number of `\x08` and length of lines between `\r`.

Alternatively we can simply ignore it and believe the users would just get used to it.

**Comment by ldoktor** [comment] 2015-11-06 23:33
PS: I noticed that we remove the echoed command if found in the log output. This took me also a while. So currently we have those variants:

1. disable echo - nice output in the log, unusable `session-avocado-vt-*` session logs
2. set cols to a big number - nice output for most commands in booth logs
3. use the `\x08` hack to restore the output - nice outputs in booth logs, but might corrupt some outputs
4. just let users know that "echo" wraps and produces some weird characters (we can use the `3` hack to detect such situations and put the warning directly into the log)

No matter which way we choose the output is correct. The only corrupted part is the echoed command.

**Comment by ldoktor** [comment] 2015-11-06 23:35
_note: This problem is only when using "ssh". With other commands or simple "shell" everything works fine._

**Comment by lmr** [comment] 2015-11-07 02:03
@olavph so, how serious do you consider this issue? From what I gather, this is a bit of a corner case, but I'd like to hear from you.

**Comment by ldoktor** [comment] 2015-11-07 05:40
Well not exactly an corner case, it's just hard to spot. Most people just see command which looks +- like what they expect and are satisfied. I remember we worked on the issue with weird characters (`\x08`) in the output. I think it was either Ruda or even Jiří, who used the `replace` to get rid of it...

**Comment by ldoktor** [comment] 2015-11-07 05:53
Actually there is a simpler solution (I remember using this approach in autotest-docker, when I needed to detach from the container and reattach it back). We can spawn "shell" session instead of "ssh" and execute "ssh" in it. This magically works (which means our `tty` does not set everything properly)

```
diff --git a/virttest/remote.py b/virttest/remote.py
index 099e7cf..c8ae4e8 100644
--- a/virttest/remote.py
+++ b/virttest/remote.py
@@ -245,8 +245,12 @@ def remote_login(client, host, port, username, password, prompt, linesep="\n",
         raise LoginBadClientError(client)
 
     logging.debug("Login command: '%s'", cmd)
-    session = aexpect.ShellSession(cmd, linesep=linesep, prompt=prompt,
+    session = aexpect.ShellSession("/bin/sh", linesep=linesep, prompt=prompt,
                                    status_test_command=status_test_command)
+    data = session.read_nonblocking(10, 10)
+    if not data:
+        raise LoginError("No output in host shell in 10s")
+    session.sendline(cmd + "; RET=$?; echo connection terminated with $?; exit $?")
     try:
         handle_prompts(session, username, password, prompt, timeout)
     except Exception:
```

**Comment by ldoktor** [comment] 2015-11-07 05:56
^^ this has one drawback, someone might theoretically trick `session` into escaping into host and then corrupt the host. To do that he'd have to modify either `user_name`, `host` or `port` into something with `;` or `&&` or `||`...

**Comment by ldoktor** [comment] 2015-11-07 05:57
Oh no, I used the modified `aexpect`. The patch above does not work. It uses the `cols` as before... please ignore that message. So the only solutions are still https://github.com/avocado-framework/avocado-vt/issues/231#issuecomment-154576892

**Comment by olavph** [comment] 2015-11-09 11:49
In my case, I'd prefer the first solution: disable echo - nice output in the log, unusable session-avocado-vt-* session logs, as it makes sure the output is always correct.
I am parsing the command outputs automatically, so it's important that they come  in the expected format. But I understand that the session logs may be useful in other use cases.
The second solution should also be fine, with a very big number.

**Comment by alanoe** [comment] 2016-11-07 22:50
One year has passed. Any updates on this? Have we reached the conclusion that this will not be fixed?

**Comment by ldoktor** [comment] 2016-11-10 09:17
Hello @alanoe, I don't remember how this proceed, but when I tried to reproduce it today `aexpect` didn't use the echo, therefor the first solution (`disable echo - nice output in the log, unusable session-avocado-vt-* session logs`) was probably applied. I briefly looked into the code, but I haven't found the commit, though.

Tested on F23 with JeOS.23
* aexpect: aca459d332c90c8d2db521819a4e2f83fa0b7614
* avocado-vt: 2c249c1b3c94a1f2ba96b10032d10f70efa1ee9b

and I used modified `boot` test which printed:

```python
print session.cmd("echo %s" % ("a" * 255))
print session.cmd("echo %s" % ("a" * 255))
```

and the log was:

```
2016-11-10 10:08:40: Warning: Permanently added '[192.168.2.2]:5000' (ECDSA) to the list of known hosts.
2016-11-10 10:08:40: root@192.168.2.2's password:
2016-11-10 10:08:40: [root@atest-guest ~]#
2016-11-10 10:08:44: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2016-11-10 10:08:44: [root@atest-guest ~]#
2016-11-10 10:08:44: 0
2016-11-10 10:08:45: [root@atest-guest ~]#
2016-11-10 10:08:48: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2016-11-10 10:08:48: [root@atest-guest ~]#
2016-11-10 10:08:48: 0
2016-11-10 10:08:48: [root@atest-guest ~]#
2016-11-10 10:13:30: (Process terminated with status 0)
2016-11-10 10:13:38: Warning: Permanently added '[192.168.2.2]:5000' (ECDSA) to the list of known hosts.
2016-11-10 10:13:38: root@192.168.2.2's password:
2016-11-10 10:13:38: Last login: Thu Nov 10 04:08:39 2016 from 192.168.2.2
2016-11-10 10:13:38: [root@atest-guest ~]#
2016-11-10 10:13:38: (Process terminated with status 0)
```

When I force-enabled `echo` by using `aexpect.ShellSession(..., echo=True)` in `virttest.remote`, the extra characters were there...

```
2016-11-10 10:04:15: Warning: Permanently added '[192.168.2.2]:5000' (ECDSA) to the list of known hosts.
2016-11-10 10:04:15: root@192.168.2.2's password:
2016-11-10 10:04:15: [root@atest-guest ~]#
2016-11-10 10:04:18: echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaa                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................
               .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         ....
.....................aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         .......................
..aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         .........................aaaaaaaaaaaaaaaaa
aaaaaaaa.........................                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa...........
..............                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................
                    .........................aaaaaaaaaaaaaaaaaaaaaa
2016-11-10 10:04:18: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2016-11-10 10:04:18: [root@atest-guest ~]#
2016-11-10 10:04:18: echo $?
2016-11-10 10:04:18: 0
2016-11-10 10:04:18: [root@atest-guest ~]#
2016-11-10 10:04:25: echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaa                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................
               .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         ....
.....................aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         .......................
..aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         .........................aaaaaaaaaaaaaaaaa
aaaaaaaa.........................                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa...........
..............                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................
                    .........................aaaaaaaaaaaaaaaaaaaaaa
2016-11-10 10:04:25: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2016-11-10 10:04:25: [root@atest-guest ~]#
2016-11-10 10:04:25: echo $?
2016-11-10 10:04:25: 0
2016-11-10 10:04:25: [root@atest-guest ~]#
2016-11-10 10:04:29: echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaa                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................
               .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         ....
.....................aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         .......................
..aaaaaaaaaaaaaaaaaaaaaaaaa.........................                         .........................aaaaaaaaaaaaaaaaa
aaaaaaaa.........................                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa...........
..............                         .........................aaaaaaaaaaaaaaaaaaaaaaaaa.........................
                    .........................aaaaaaaaaaaaaaaaaaaaaa
2016-11-10 10:04:29: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
2016-11-10 10:04:29: [root@atest-guest ~]#
2016-11-10 10:04:29: echo $?
2016-11-10 10:04:29: 0
2016-11-10 10:04:29: [root@atest-guest ~]#
2016-11-10 10:04:30: (Process terminated with status 0)
```

Please let me know if your virttest behaves the same way (I mean that this issue does not persists, you don't need to try to reproduce it)

**Comment by olavphibm** [comment] 2016-11-14 18:11
I've tried removing my workaround, but the issue still exists in our current setup. We have avocado/avocado-vt release 40.0 and aexpect version 1.2.0. Updating to 43.0 led to some problems, so we're probably not gonna do this right now.
@ldoktor Is it possible that you fixed it in your recent aexpect commits?
Maybe https://github.com/autotest/aexpect/commit/5aa7d475ca5f095057485ee61f98d989ee41872c

**Comment by ldoktor** [comment] 2016-11-16 13:23
Hello @olavph, the fix was not in aexpect, but in the guest os itself:

```
$ avocado run --vt-guest-os Fedora.20.x86_64 --vt-qemu-bin /usr/local/bin/qemu-system-x86_64 --show-job-log boot
...
Sending command: echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Sending command: echo $?
echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa   
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

While on the latest JeOS (Fedora 23)

```
$ avocado run --vt-qemu-bin /usr/local/bin/qemu-system-x86_64 --show-job-log boot
...
Sending command: echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Sending command: echo $?
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

With this in mind I don't think we should try working around a guest issue, but you can try looking for the guest fix and ask your distro provider to apply the fix. @lmr @clebergnu any thoughts?

**Comment by lmr** [comment] 2016-11-16 13:32
I agree that we shouldn't try to work around a guest issue, although it may depend on @olavph's team needs, actually.

@olavph and @alanoe, is this something you're noticing on a custom OS? Does simply moving onto using the latest JeOS work for you?

**Comment by ldoktor** [comment] 2016-11-16 13:58
I tried RHEL.7.2 and the bug is there. Let me try 7.3, but eventually it should get fixed as it was fixed in Fedora already...

**Comment by olavphibm** [comment] 2016-11-16 14:07
We are currently executing our tests with avocado in a PowerKVM big endian system, which is kind of outdated. This is not a blocker for us, since we do have a workaround and we could move to a newer machine if really needed.
I think you can close this.
@alanoe do you agree?

**Comment by ldoktor** [comment] 2016-11-16 15:40
The RHEL.7.3 still suffers from this issue. It'd be nice to know what issue fixes it and what is the status in RHEL. Still it's a guest-issue so I think we should close this one. There are few suggestions how to avoid it so people can use it on their own risk.

**Comment by alanoe** [comment] 2016-11-16 16:49
Guest issue = bug in QEMU or libvirt? Someone can point where is the patch which fixes it?

LD> The RHEL.7.3 still suffers from this issue. (...) There are few suggestions how to avoid it so people can use it on their own risk.

RHEL 7.3 is the latest RHEL version. If this bug is expected in it, shouldn't Avocado doc at least mention the bug and point to the possible workarounds?

**Comment by ldoktor** [comment] 2016-11-18 09:29
Hello @alanoe, I tried to find the simple reproducer and as a matter of fact it's because RHEL.7 ignores the echo setting. I filed a bug here: https://bugzilla.redhat.com/show_bug.cgi?id=1396400 and hopefully we'll get some answers.

As for the documentation, yes, it's a good and useful idea. What would you say about this: https://github.com/avocado-framework/avocado-vt/pull/777

**Comment by ldoktor** [comment] 2016-11-18 16:59
OK, let's close this one as the documentation fix was accepted. I'll follow up on the bz and if any useful info pops out, I'll add it here (or address in avocado-vt sources)

**Closed by ldoktor** 2016-11-18 16:59 UTC
